---
Name: content-creator
After:
  - 'cms-config'
---
KhalsaJio\ContentCreator\Services\LLMService:
  default_provider: 'OpenAI'
  providers:
    OpenAI:
      api_key: '`OPENAI_API_KEY`'
      model: 'gpt-4o'
      max_tokens: 4000
      temperature: 0.7
    Claude:
      api_key: '`ANTHROPIC_API_KEY`'
      model: 'claude-3-opus-20240229'
      max_tokens: 4000
      temperature: 0.7
    Custom:
      class: '\\Your\\Custom\\LLMProvider'
      api_key: '`CUSTOM_LLM_API_KEY`'

KhalsaJio\ContentCreator\Extensions\ContentCreatorExtension:
  enabled_page_types:
    - SilverStripe\CMS\Model\SiteTree
  excluded_page_types:
    - SilverStripe\ErrorPage\ErrorPage

# Register the extension to SiteTree
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - KhalsaJio\ContentCreator\Extensions\ContentCreatorExtension

# Register our JavaScript and CSS
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'silverstripe/admin:client/dist/js/bundle.js' # Ensure admin JS is loaded first
    - 'khalsa-jio/silverstripe-content-creator:client/dist/js/bundle.js'
  extra_requirements_css:
    - 'khalsa-jio/silverstripe-content-creator:client/dist/styles/bundle.css'
