name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read
      actions: write
    with:
      simple_matrix: true